sudo: false
language: "node_js"
node_js:
  - "4"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_script:
  - npm install standard
  - standard
script:
  - npm install istanbul
  - istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- --recursive
after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls
  - node test/screenshots.js
  - git add screenshots
  - git commit -m "Added screenshots"
  - git push
  